import Navigation from '@/components/navigation/Navigation';
import '@/styles/main.scss';

import { Work_Sans, Anton } from 'next/font/google';

const work_sans = Work_Sans({
  subsets: ['latin'],
  display: 'swap'
});

const anton = Anton({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={work_sans.className}>
        <Navigation />
        <main>{children}</main>
      </body>
    </html>
  );
}
